name: Cypress Tests

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  demo-chrome-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - run: npm install

      - run: npx cypress info

      - name: "Demo Tests - Chrome"
        uses: cypress-io/github-action@v2
        with:
          browser: chrome

  demo-chrome-mobile-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - run: npm install

      - run: npx cypress info

      - name: "Demo Tests - Chrome - Mobile"
        uses: cypress-io/github-action@v2
        with:
          config: "viewportWidth=375,viewportHeight=667"
          browser: chrome

  demo-firefox-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node14.16.0-chrome89-ff86
      options: --user 1001
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - run: npm install

      - run: npx cypress info

      - name: "Demo Tests - Firefox"
        uses: cypress-io/github-action@v2
        with:
          browser: firefox

  demo-firefox-mobile-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node14.16.0-chrome89-ff86
      options: --user 1001
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - run: npm install

      - run: npx cypress info

      - name: "Demo Tests - Firefox - Mobile"
        uses: cypress-io/github-action@v2
        with:
          config: "viewportWidth=375,viewportHeight=667"
          browser: firefox

  demo-windows-tests:
    runs-on: windows-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - run: npm install

      - run: npx cypress info

      - name: "Demo Tests - Electron - Windows"
        uses: cypress-io/github-action@v2
